FROM ruby
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
RUN mkdir -p /opt/src/sga_core
WORKDIR /opt/src/sga_core
COPY Gemfile /opt/src/sga_core/Gemfile
COPY Gemfile.lock /opt/src/sga_core/Gemfile.lock
RUN bundle install
COPY . /opt/src/sga_core